/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-05-24 13:51:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>\r\n");
      out.write("<script src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js'></script>\r\n");
      out.write("<link href='https://use.fontawesome.com/releases/v5.7.2/css/all.css'>\r\n");
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>CheckoutPage</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("head,\r\n");
      out.write("body {\r\n");
      out.write("    background-color: #FFCCBC\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("    margin-top: 40px;\r\n");
      out.write("    margin-bottom: 40px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("    width: 100%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-title {\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    margin-top: 25px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register {\r\n");
      out.write("    font-size: 10px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    bottom: 5px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cvc {\r\n");
      out.write("    width: 2.5em;\r\n");
      out.write("    position: absolute\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding-left: 4px;\r\n");
      out.write("    background-color: #f7f1f1;\r\n");
      out.write("    font-size: 15px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-body {\r\n");
      out.write("    background-color: #f7f1f1\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("    background-color: #00BCD4;\r\n");
      out.write("    color: white\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer:hover {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    background-color: #0097A7\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".numbr {\r\n");
      out.write("    border-bottom: 1px solid #c1bcbc;\r\n");
      out.write("    padding-bottom: 8px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".line2 {\r\n");
      out.write("    border-bottom: 1px solid #c1bcbc;\r\n");
      out.write("    padding-bottom: 8px;\r\n");
      out.write("    padding-left: 0px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input.focus,\r\n");
      out.write("input:focus {\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    box-shadow: none !important\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".numbr.numbr.hover,\r\n");
      out.write(".numbr:hover {\r\n");
      out.write("    border-bottom: 1px solid aqua\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".line2.hover,\r\n");
      out.write(".line2:hover {\r\n");
      out.write("    border-bottom: 1px solid aqua\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fa-lock {\r\n");
      out.write("    margin-right: 10px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".order {\r\n");
      out.write("    margin-top: 10px\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class='container'>\r\n");
      out.write("    <div class=\"card mx-auto col-md-5 col-8 mt-3 p-0\"> <img class='mx-auto pic' src=\"https://i.imgur.com/kXUgBQZ.jpg\" />\r\n");
      out.write("        <div class=\"card-title d-flex px-4\">\r\n");
      out.write("            <p class=\"item text-muted\">Barcelona<label class=\"register\">&reg;</label> Chair</p>\r\n");
      out.write("            <p>$5760</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <p class=\"text-muted\">Your payment details</p>\r\n");
      out.write("            <div class=\"numbr mb-3\"> <i class=\" col-1 fas fa-credit-card text-muted p-0\"></i> <input class=\"col-10 p-0\" type=\"text\" placeholder=\"Card Number\"> </div>\r\n");
      out.write("            <div class=\"line2 col-lg-12 col-12 mb-4\"> <i class=\"col-1 far fa-calendar-minus text-muted p-0\"></i> <input class=\"cal col-5 p-0\" type=\"text\" placeholder=\"MM/YY\"> <i class=\"col-1 fas fa-lock text-muted\"></i> <input class=\"cvc col-5 p-0\" type=\"text\" placeholder=\"CVC\"> </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer text-center p-0\">\r\n");
      out.write("            <div class=\"col-lg-12 col-12 p-0\">\r\n");
      out.write("                <p class=\"order\">Order Now</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
