/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-05-23 13:59:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/All%20about%20Spring/AAHAA/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Shopify_Frontend/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098691290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1616332259262L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>USER Home</title>\r\n");
      out.write("<link href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>\r\n");
      out.write("<script src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js'></script>\r\n");
      out.write("<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css'>\r\n");
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("    background: linear-gradient(to right, #c04848, #480048);\r\n");
      out.write("    min-height: 100vh\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-gray {\r\n");
      out.write("    color: #aaa\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("    height: 170px;\r\n");
      out.write("    width: 140px\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container py-5\">\r\n");
      out.write("    <div class=\"row text-center text-white mb-5\">\r\n");
      out.write("        <div class=\"col-lg-7 mx-auto\">\r\n");
      out.write("            <h1 class=\"display-4\">Product List</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("            <!-- List group-->\r\n");
      out.write("            <ul class=\"list-group shadow\">\r\n");
      out.write("                <!-- list group item-->\r\n");
      out.write("                <li class=\"list-group-item\">\r\n");
      out.write("                    <!-- Custom content-->\r\n");
      out.write("                    <div class=\"media align-items-lg-center flex-column flex-lg-row p-3\">\r\n");
      out.write("                        <div class=\"media-body order-2 order-lg-1\">\r\n");
      out.write("                            <h5 class=\"mt-0 font-weight-bold mb-2\">Apple iPhone XR (Red, 128 GB)</h5>\r\n");
      out.write("                            <p class=\"font-italic text-muted mb-0 small\">128 GB ROM | 15.49 cm (6.1 inch) Display 12MP Rear Camera | 7MP Front Camera A12 Bionic Chip Processor</p>\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-between mt-1\">\r\n");
      out.write("                                <h6 class=\"font-weight-bold my-2\">â¹64,999</h6>\r\n");
      out.write("                                <ul class=\"list-inline small\">\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star-o text-gray\"></i></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div><a href=\"Iphone\" target=\"_blank\"><img src=\"https://i.imgur.com/KFojDGa.jpg\" alt=\"Generic placeholder image\" width=\"200\" class=\"ml-lg-5 order-1 order-lg-2\"></a>\r\n");
      out.write("                    </div> <!-- End -->\r\n");
      out.write("                </li> <!-- End -->\r\n");
      out.write("                <!-- list group item-->\r\n");
      out.write("                <li class=\"list-group-item\">\r\n");
      out.write("                    <!-- Custom content-->\r\n");
      out.write("                    <div class=\"media align-items-lg-center flex-column flex-lg-row p-3\">\r\n");
      out.write("                        <div class=\"media-body order-2 order-lg-1\">\r\n");
      out.write("                            <h5 class=\"mt-0 font-weight-bold mb-2\">Apple iPhone XS (Silver, 64 GB)</h5>\r\n");
      out.write("                            <p class=\"font-italic text-muted mb-0 small\">64 GB ROM | 14.73 cm (5.8 inch) Super Retina HD Display 12MP + 12MP | 7MP Front Camera A12 Bionic Chip Processor</p>\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-between mt-1\">\r\n");
      out.write("                                <h6 class=\"font-weight-bold my-2\">â¹99,900</h6>\r\n");
      out.write("                                <ul class=\"list-inline small\">\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div><img src=\"https://i.imgur.com/KFojDGa.jpg\" alt=\"Generic placeholder image\" width=\"200\" class=\"ml-lg-5 order-1 order-lg-2\">\r\n");
      out.write("                    </div> <!-- End -->\r\n");
      out.write("                </li> <!-- End -->\r\n");
      out.write("                <!-- list group item -->\r\n");
      out.write("                <li class=\"list-group-item\">\r\n");
      out.write("                    <!-- Custom content-->\r\n");
      out.write("                    <div class=\"media align-items-lg-center flex-column flex-lg-row p-3\">\r\n");
      out.write("                        <div class=\"media-body order-2 order-lg-1\">\r\n");
      out.write("                            <h5 class=\"mt-0 font-weight-bold mb-2\">Apple iPhone XS Max (Gold, 64 GB)</h5>\r\n");
      out.write("                            <p class=\"font-italic text-muted mb-0 small\">64 GB ROM | 16.51 cm (6.5 inch) Super Retina HD Display 12MP + 12MP | 7MP Front Camera A12 Bionic Chip Processor</p>\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-between mt-1\">\r\n");
      out.write("                                <h6 class=\"font-weight-bold my-2\">â¹1,09,900</h6>\r\n");
      out.write("                                <ul class=\"list-inline small\">\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star-o text-gray\"></i></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div><img src=\"https://i.imgur.com/KFojDGa.jpg\" alt=\"Generic placeholder image\" width=\"200\" class=\"ml-lg-5 order-1 order-lg-2\">\r\n");
      out.write("                    </div> <!-- End -->\r\n");
      out.write("                </li> <!-- End -->\r\n");
      out.write("                <!-- list group item -->\r\n");
      out.write("                <li class=\"list-group-item\">\r\n");
      out.write("                    <!-- Custom content-->\r\n");
      out.write("                    <div class=\"media align-items-lg-center flex-column flex-lg-row p-3\">\r\n");
      out.write("                        <div class=\"media-body order-2 order-lg-1\">\r\n");
      out.write("                            <h5 class=\"mt-0 font-weight-bold mb-2\">OnePlus 7 Pro (Almond, 256 GB)</h5>\r\n");
      out.write("                            <p class=\"font-italic text-muted mb-0 small\">Rear Camera|48MP (Primary)+ 8MP (Tele-photo)+16MP (ultrawide)| Front Camera|16 MP POP-UP Camera|8GB RAM|Android pie</p>\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-between mt-1\">\r\n");
      out.write("                                <h6 class=\"font-weight-bold my-2\">â¹ 52,999</h6>\r\n");
      out.write("                                <ul class=\"list-inline small\">\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                    <li class=\"list-inline-item m-0\"><i class=\"fa fa-star text-success\"></i></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div><img src=\"https://i.imgur.com/6IUbEME.jpg\" alt=\"Generic placeholder image\" width=\"200\" class=\"ml-lg-5 order-1 order-lg-2\">\r\n");
      out.write("                    </div> <!-- End -->\r\n");
      out.write("                </li> <!-- End -->\r\n");
      out.write("            </ul> <!-- End -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
